# Generated by Django 3.0.4 on 2020-03-19 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0002_auto_20200320_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_content', models.CharField(max_length=2000)),
                ('attachment_creation_date', models.DateField()),
                ('attachment_type', models.CharField(max_length=50)),
                ('attachment_visible_date', models.DateField()),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pznsi.Comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pznsi.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
