# Generated by Django 3.0.4 on 2020-03-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0004_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_closing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_file_content', models.CharField(max_length=2000)),
                ('repository_file_date_created', models.DateField()),
                ('repository_file_status', models.CharField(max_length=100)),
                ('attachments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pznsi.Attachments')),
            ],
        ),
    ]
