# Generated by Django 3.0.4 on 2020-03-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0007_auto_20200321_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='project_password',
            new_name='environment_password',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='project_creation_date',
        ),
        migrations.AddField(
            model_name='environment',
            name='environment_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='attachment_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='attachment_visible_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_file_date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='vote_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
