# Generated by Django 3.0.4 on 2020-05-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0009_auto_20200429_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='environment_covers'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_covers'),
        ),
    ]
