# Generated by Django 3.0.5 on 2020-05-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0010_auto_20200507_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project_instance', 'view project instance'), ('edit_project_instance', 'edit project instance'), ('vote', 'vote'))},
        ),
    ]
