# Generated by Django 3.0.5 on 2020-05-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0011_auto_20200514_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'permissions': (('view_environment_instance', 'view environment instance'), ('edit_environment_instance', 'edit environment instance'))},
        ),
    ]
