# Generated by Django 3.0.5 on 2020-05-16 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0013_auto_20200516_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=2000)),
                ('content', models.FileField(blank=True, null=True, upload_to='attachments')),
                ('attachment_creation_date', models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True)),
                ('attachment_type', models.CharField(max_length=50)),
                ('attachment_visible_date', models.DateField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pznsi.Comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pznsi.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='repository',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pznsi.Attachment'),
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
    ]
