# Generated by Django 3.0.5 on 2020-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0014_auto_20200516_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(default='file', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
