# Generated by Django 3.0.5 on 2020-05-16 19:17

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0015_auto_20200516_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_content',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
    ]
