# Generated by Django 3.0.5 on 2020-05-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0016_auto_20200516_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pznsi.Project'),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_content',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
