# Generated by Django 3.0.5 on 2020-05-19 18:09

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0017_auto_20200516_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_file_date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
    ]
