# Generated by Django 3.0.5 on 2020-05-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0011_auto_20200513_2234'),
        ('pznsi', '0018_auto_20200519_2009'),
    ]

    operations = [
    ]
