# Generated by Django 3.0.5 on 2020-05-21 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0020_auto_20200520_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='repository_files')),
                ('file_date_created', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='repository',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
