# Generated by Django 3.0.5 on 2020-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0021_auto_20200521_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='visible_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
