# Generated by Django 3.0.5 on 2020-05-21 17:17

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('pznsi', '0022_repositoryfile_visible_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfile',
            name='file_date_created',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
